
import React from 'react';
import { motion } from 'framer-motion';
import { Helmet } from 'react-helmet';

const PrivacyPolicy = () => {
  return (
    <>
      <Helmet>
        <title>Privacy Policy | Health Guardian</title>
      </Helmet>
      <div className="container mx-auto px-4 py-12">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          className="max-w-4xl mx-auto"
        >
          <h1 className="text-4xl font-bold mb-8">Privacy Policy</h1>
          
          <div className="prose prose-lg max-w-none">
            <p className="lead">Last updated: {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}</p>
            
            <h2>1. Introduction</h2>
            <p>
              Health Guardian ("we," "our," or "us") is committed to protecting your privacy. This Privacy Policy explains how your personal information is collected, used, and disclosed by Health Guardian.
            </p>
            <p>
              This Privacy Policy applies to our website, and its associated subdomains (collectively, our "Service") alongside our application, Health Guardian. By accessing or using our Service, you signify that you have read, understood, and agree to our collection, storage, use, and disclosure of your personal information as described in this Privacy Policy and our Terms of Service.
            </p>
            
            <h2>2. Definitions and Key Terms</h2>
            <p>
              For this Privacy Policy:
            </p>
            <ul>
              <li><strong>Cookie:</strong> small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.</li>
              <li><strong>Company:</strong> when this policy mentions "Company," "we," "us," or "our," it refers to Health Guardian that is responsible for your information under this Privacy Policy.</li>
              <li><strong>Personal Data:</strong> any information that directly, indirectly, or in connection with other information — including a personal identification number — allows for the identification or identifiability of a natural person.</li>
              <li><strong>Service:</strong> refers to the application or the website or both.</li>
              <li><strong>Third-party service:</strong> refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.</li>
              <li><strong>Website:</strong> Health Guardian's site, which can be accessed via this URL: healthguardian.com</li>
              <li><strong>You:</strong> a person or entity that is registered with Health Guardian to use the Services.</li>
            </ul>
            
            <h2>3. Information We Collect</h2>
            <p>
              We collect information from you when you visit our app, register on our site, place an order, subscribe to our newsletter, respond to a survey or fill out a form.
            </p>
            <ul>
              <li>Name / Username</li>
              <li>Email Addresses</li>
              <li>Age</li>
              <li>Gender</li>
              <li>Health and fitness data</li>
              <li>Food consumption data</li>
              <li>Exercise data</li>
            </ul>
            
            <h2>4. How We Use Your Information</h2>
            <p>
              We use the information we collect in various ways, including to:
            </p>
            <ul>
              <li>Provide, operate, and maintain our app</li>
              <li>Improve, personalize, and expand our app</li>
              <li>Understand and analyze how you use our app</li>
              <li>Develop new products, services, features, and functionality</li>
              <li>Communicate with you, either directly or through one of our partners, including for customer service, to provide you with updates and other information relating to the app, and for marketing and promotional purposes</li>
              <li>Send you emails</li>
              <li>Find and prevent fraud</li>
              <li>Personalize your experience and to allow us to deliver the type of content and product offerings in which you are most interested</li>
            </ul>
            
            <h2>5. Data Retention</h2>
            <p>
              We will retain your personal information only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your information to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our policies.
            </p>
            
            <h2>6. Your Rights</h2>
            <p>
              You have the right to request access to the personal information we collect from you, change that information, or delete it. To request to review, update, or delete your personal information, please submit a request to our contact email.
            </p>
            
            <h2>7. Contact Us</h2>
            <p>
              If you have any questions about this Privacy Policy, please contact us at privacy@healthguardian.com.
            </p>
          </div>
        </motion.div>
      </div>
    </>
  );
};

export default PrivacyPolicy;
